site_name: ServiceX
nav:
    - Home: index.md
    - Introduction: introduction.md
    - 'User Guide':
        - Getting started: user/getting-started.md
        - Specifying a request: user/requests.md
        - Outreach: user/outreach.md
    - 'Deployment Guide':
<<<<<<< HEAD
        - Introduction: deployment/introduction.md
        - Basic deployments: deployment/basic.md
        - Production deployments: deployment/production.md
        - Reference: deployment/reference.md
=======
        - Deployment: deployment.md
>>>>>>> Add sections to docs nav
    - 'Developer Guide':
        - Development: development.md
theme: readthedocs
