site_name: ServiceX
nav:
    - Home: index.md
    - Introduction: introduction.md
    - 'User Guide':
        - Getting started: user/getting-started.md
        - Specifying a request: user/requests.md
        - Outreach: user/outreach.md
        - Notebook: test.ipynb
    - 'Deployment Guide':
        - Introduction: deployment/introduction.md
        - Basic deployments: deployment/basic.md
        - Production deployments: deployment/production.md
        - Reference: deployment/reference.md
    - 'Developer Guide':
        - Development: development/development.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
plugins:
    - mkdocs-jupyter