site_name: ServiceX
nav:
    - Home: index.md
    - Introduction: introduction.md
    - 'User Guide':
        - Getting started: user/getting-started.md
        - Specifying a request: user/requests.md
        - Outreach: user/outreach.md
        # - Func-ADL Intro: user/func_adl_intro.ipynb
        # - TCut Intro: user/tcut_intro.ipynb
        # - Advanced xAOD with Func-ADL: user/func_adl_xaod.ipynb
    - 'Deployment Guide':
        - Introduction: deployment/introduction.md
        - Basic deployments: deployment/basic.md
        - Production deployments: deployment/production.md
        - Reference: deployment/reference.md
    - 'Developer Guide':
        - Development: development/development.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
plugins:
    - mkdocs-jupyter
