# Default values for logging.

servicex:
  # namespace where you have servicex deployed
  namespace:
    - servicex
    - servicex-int-uproot
    - servicex-int-xaod
    - servicex-testing-1
    - servicex-testing-2
    - servicex-testing-3

elasticsearch:
  host: "atlas-kibana.mwt2.org"
  port: "9200"
  user: river-dev-logs
  pass: river-dev-logs
  protocol: https

kibana:
  host: https://atlas-kibana.mwt2.org:5601
  dashboards:
    enabled: true
    index: .kibana-dev
