apiVersion: v1
description: Install ServiceX deployment - HEP Columnar Data Delivery Service
name: servicex
version: 1.0.32-RC.1
appVersion: 20220926-1720-stable
maintainers:
  - name: BenGalewsky
    url: https://github.com/BenGalewsky
  - name: sthapa
    url: https://github.com/sthapa
  - name: ivukotic
    url: https://github.com/ivukotic
