apiVersion: v1
appVersion: 20220928-0107-stable
description: Install ServiceX deployment - HEP Columnar Data Delivery Service
maintainers:
- name: BenGalewsky
  url: https://github.com/BenGalewsky
- name: sthapa
  url: https://github.com/sthapa
- name: ivukotic
  url: https://github.com/ivukotic
name: servicex
version: 1.0.32
