dependencies:
  - name: rabbitmq
    version: 3.8.*
    repository: https://charts.bitnami.com/bitnami/
  - name: minio
    version: 5.0.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: objectStore.enabled
  - name: postgresql
    version: 8.3.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgres.enabled
