app:
  adminEmail: admin@example.com
  auth: false
  authExpires: 21600
  checksImage: ncsa/checks:latest
  defaultDIDFinderScheme: null
  globusClientID: null
  globusClientSecret: null
  image: sslhep/servicex_app
  ingress:
    class: nginx
    defaultBackend: default-http-backend
    enabled: false
    host: servicex.ssl-hep.org
    tls:
      clusterIssuer: null
      enabled: false
      secretName: '{{.Release.Name}}-app-tls'
  logLevel: WARNING
  mailgunApiKey: null
  mailgunDomain: null
  pullPolicy: Always
  rabbitmq:
    retries: 12
    retry_interval: 10
  replicas: 1
  tag: 20220928-0107-stable
  tokenExpires: false
  validateTransformerImage: true
codeGen:
  enabled: true
  image: sslhep/servicex_code_gen_atlas_xaod
  pullPolicy: Always
  tag: 20220928-0107-stable
didFinder:
  CERNOpenData:
    cachePrefix: null
    enabled: true
    image: sslhep/servicex-did-finder-cernopendata
    pullPolicy: Always
    tag: 20220926-1720-stable
  rucio:
    auth_host: https://voatlasrucio-auth-prod.cern.ch:443
    cachePrefix: null
    enabled: true
    image: sslhep/servicex-did-finder
    memcache:
      enabled: true
      image: memcached
      tag: alpine
      ttl: 86400
    pullPolicy: Always
    reportLogicalFiles: false
    rucio_host: https://voatlasrucio-server-prod.cern.ch:443
    servicex_latitude: 41.78
    servicex_longitude: -87.7
    tag: 20220926-1720-stable
gridAccount: <your account>
logging:
  logstash:
    enabled: true
    host: servicex.atlas-ml.org
    port: 5959
    protocol: TCP
minio:
  auth:
    rootPassword: leftfoot1
    rootUser: miniouser
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 60
  persistence:
    enabled: false
noCerts: false
objectStore:
  enabled: true
  internal: true
  publicClientUseTLS: true
  publicURL: null
  useTLS: false
postgres:
  enabled: false
postgresql:
  global:
    postgresql:
      auth:
        database: servicex
        postgresPassword: leftfoot1
  primary:
    persistence:
      enabled: false
rabbitmq:
  auth:
    password: leftfoot1
  persistence:
    enabled: false
  volumePermissions:
    enabled: true
rbacEnabled: true
secrets: null
transformer:
  autoscaler:
    cpuScaleThreshold: 30
    enabled: true
    maxReplicas: 20
    minReplicas: 1
  cpuLimit: 1
  defaultTransformerImage: sslhep/servicex_func_adl_xaod_transformer
  defaultTransformerTag: 20220928-0107-stable
  persistence:
    existingClaim: null
    subdir: null
  priorityClassName: null
  pullPolicy: Always
x509Secrets:
  image: sslhep/x509-secrets
  initImage: alpine:3.6
  pullPolicy: Always
  tag: 20220928-0107-stable
  vomsOrg: atlas
