apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer
  namespace: analysis
  labels:
    app: consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: analysis
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: sslhep/servicex-server:analysis
        # command: ["python"]
        # args: ["consumer.py"]
        resources:
          limits:
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "200Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: REQ_ID
          value: "Oep7NWwBMWltPFRMSe5E"
        - name: GROUP
          value: "Ilija_Group"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name