apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer
  namespace: analysis
  labels:
    app: redis-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-consumer
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-consumer
  namespace: analysis
  labels:
    app: redis-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-consumer
  template:
    metadata:
      labels:
        app: redis-consumer
    spec:
      containers:
      - name: redis-consumer
        image: sslhep/servicex-server:redis_monitor
        command: ["python"]
        args: ["consumer.py"]
        resources:
          limits:
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "200Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: REQ_ID
          value: "Kso2KmwBMWltPFRMMgVl"
        - name: GROUP
          value: "Ilija_Group"