apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-monitor
  namespace: redis
  labels:
    app: redis-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-monitor
  template:
    metadata:
      labels:
        app: redis-monitor
    spec:
      containers:
      - name: redis-monitor
        image: sslhep/servicex-server:redis_monitor
        # command: ["sleep"]
        # args: ["9999999999"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "200Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"