name: CI/CD

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
        id: extract_tag_name

      - name: Build Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: sslhep/servicex_lite:${{ steps.extract_tag_name.outputs.imagetag }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        #   tag: "${GITHUB_REF##*/}"
