{{- if .Values.app.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.app.ingress.class }}
    {{- if .Values.app.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.app.ingress.tls.clusterIssuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
  labels:
    app: {{ .Release.Name }}-servicex
  name: {{ .Release.Name }}-servicex
spec:
  {{- if .Values.app.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.app.ingress.host }}
    secretName: {{ tpl .Values.app.ingress.tls.secretName . }}
  {{- end }}
  rules:
  - host: {{ .Release.Name }}.{{ .Values.app.ingress.host }}
    http:
      paths:
      - path: /servicex/internal
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.ingress.defaultBackend }}
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-servicex-app
            port: 
              number: 8000
{{- end }}
