{{- if and .Values.webdav.enabled .Values.webdav.internal .Values.webdav.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webdav-secret
  labels:
    app: {{ .Release.Name }}-webdav
type: Opaque
stringData:
  BASIC_USERS: "{{ .Values.webdav.auth.username }}:{{ .Values.webdav.auth.password }}"
{{- end }}
