version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/code_generator_TopCPToolkit"
      - "/code_generator_funcadl_uproot"
      - "/code_generator_funcadl_xAOD"
      - "/code_generator_python"
      - "/code_generator_raw_uproot"
      - "/did_finder_atlasopenmagic"
      - "/did_finder_cernopendata"
      - "/did_finder_rucio"
      - "/did_finder_xrootd"
      - "/servicex_app"
      - "/transformer_sidecar"
      - "/x509_secrets"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "python"
