# These are the secrets that are needed if you want to override values
# in a secure way
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: servicex_secrets
data:
  globusClientID: <<client ID>>
  globusClientSecret: <<secret key>>
  secretKey: <<secret key for app>>
  jwtSecretKey: <<jwtSecretKey>>
  minioAccessKey: <<minioAccessKey>>
  minioSecretKey: <<minioSecretKey>>
  slackSigningSecret: <<slackSigningSecret>>
  mailgunAPIKey: <<mailgunAPIKey>>
