app:
  adminPassword: changeme
  auth: true
  slackSigningSecret: See README for instructions
  newSignupWebhook: See README for instructions
  ingress:
    enabled: true
    clusterIssuer: letsencrypt-prod
codeGen:
  image: sslhep/servicex_code_gen_func_adl_xaod
didFinder:
  pullPolicy: Always
gridAccount: bgalewsk
minio:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      acme.cert-manager.io/http01-edit-in-place: "true"
    hosts:
    - xaod-minio.servicex.ssl-hep.org
    tls:
    - hosts:
      - xaod-minio.servicex.ssl-hep.org
      secretName: xaod-minio-tls
  mode: distributed
postgres:
  enabled: true
postgresql:
  persistence:
    enabled: true
    storageClass: rook-ceph-block
preflight:
  pullPolicy: Always
rabbitmq:
  persistence:
    enabled: true
    storageClass: rook-ceph-block
  service:
    type: NodePort
transformer:
  autoscalerEnabled: true
  pullPolicy: Always
