apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: transformer
  namespace: servicex
  labels:
    app: transformer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transformer
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 2