apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: servicex
  labels:
    app: kafka-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: sslhep/servicex-server:kafka_monitor
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1000Mi"
          requests:
            cpu: "100m"
            memory: "200Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"