ARG BASE_VERSION=latest

FROM sslhep/servicex_code_gen_base:${BASE_VERSION}

COPY app.xaod.conf ./app.conf

USER servicex
ENV APP_CONFIG_FILE "/home/servicex/app.conf"

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
