apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicex-lite
  namespace: servicex-lite
  labels:
    k8s-app: servicex-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: servicex-lite
  template:
    metadata:
      labels:
        k8s-app: servicex-lite
    spec:
      containers:
        - name: servicex-lite
          image: sslhep/servicex-lite:latest
          imagePullPolicy: Always
          # command: ["sleep"]
          # args: ["infinity"]
          env:
            - name: ORIGIN_CONTEXT
              value: af-admin@af
            - name: ORIGIN_NAMESPACE
              value: servicex
            - name: SXLITE_CONTEXT
              value: kubernetes-admin@cluster.local
            - name: SXLITE_NAMESPACE
              value: servicex-lite
            - name: RMQ_USER
              value: "user"
            - name: RMQ_HOST
              value: "192.170.241.253"
            - name: INITIAL_PODS
              value: "15"
            - name: PYTHONUNBUFFERED
              value: "true"
          volumeMounts:
            - name: kubeconfig
              mountPath: /home/sxlite/.kube/
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig-secret
