---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-did-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-did-finder
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-did-finder
    spec:
      containers:
      - name: {{ .Release.Name }}-did-finder
        image: {{ .Values.didFinder.image }}:{{ .Values.didFinder.tag }}
        command: ["/usr/src/app/runme.sh"]
        imagePullPolicy: {{ .Values.didFinder.pullPolicy }}
        env:
          - name: RMQ_URI
            value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:5672
          - name: SITE
            value: {{ if .Values.didFinder.site }} --site {{ .Values.didFinder.site }} {{ end }}
          - name: DID_THREADS
            value: "{{ .Values.didFinder.threads }}"
        volumeMounts:
          - name: rucio-cfg
            mountPath: /opt/rucio/etc/
          - name: x509-secret
            mountPath: /etc/grid-security-ro
            readOnly: true

      volumes:
        - name: rucio-cfg
          configMap:
            name: {{ .Release.Name }}-rucio-config
        - name: x509-secret
          secret:
            defaultMode: 292
            secretName: {{ .Release.Name }}-x509-proxy
