#%RAML 1.0
---
title: e-BookMobile API
baseUri: http://api.e-bookmobile.com/{version}
version: v1

/users:
  /authors:
    /{authorname}:
        get:
            
  /books:
    get
        description: |
        headers: 
        body: 
        responses: 
