# These are the secrets that are needed if you want to override values
# in a secure way
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: servicex_secrets
data:
  globusClientID: <<client ID>>
  globusClientSecret: <<secret key>>
  flaskSecretKey: <<secret key for flask webapp>>
  jwtSecretKey: <<jwtSecretKey>>
  slackSigningSecret: <<slackSigningSecret>>
  slackSignupWebhook: <<slackSignupWebhook>>
  mailgunAPIKey: <<mailgunAPIKey>>
  accesskey: <<minio access key>>
  secretkey: <<minio secret key>>
  rabbitmq-password: << rabbitMQ password >>
  rabbitmq-erlang-cookie: << rabbitMQ erlang cookie >>
  postgresql-password: << postgresql password for postgres user >>
