{{- range $codeGenName, $v := .Values.codeGen }}
---
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "servicex.fullname" $ }}
      containers:
      - name: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
        image: {{ .image }}:{{ .tag }}
        env:
        - name: INSTANCE_NAME
          value: {{ $.Release.Name }}
        - name: TRANSFORMER_SCIENCE_IMAGE
          value: {{ .defaultScienceContainerImage }}:{{ .defaultScienceContainerTag }}
        {{- $compressionAlgorithm := .compressionAlgorithm | default "ZSTD" }}
        {{- $compressionLevel := .compressionLevel | default 5 }}
        - name: COMPRESSION_ALGORITHM
          value: {{ $compressionAlgorithm }}
        - name: COMPRESSION_LEVEL
          value: "{{ $compressionLevel }}"
        tty: true
        stdin: true
        imagePullPolicy: {{ .pullPolicy }}
        {{- if .resources }}
        resources:
{{ toYaml .resources | indent 10 }}
        {{- end }}
        ports:
          - containerPort: 5000
{{- end }}
{{- end }}
