{{- range $codeGenName, $v := .Values.codeGen }}
---
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
    spec:
      serviceAccountName: {{ template "servicex.fullname" $ }}
      containers:
      - name: {{ $.Release.Name }}-code-gen-{{ $codeGenName }}
        image: {{ .image }}:{{ .tag }}
        env:
        - name: INSTANCE_NAME
          value: {{ $.Release.Name }}
        - name: TRANSFORMER_SCIENCE_IMAGE
          value: {{ .defaultScienceContainerImage }}:{{ .defaultScienceContainerTag }}
        tty: true
        stdin: true
        imagePullPolicy: {{ .pullPolicy }}
        ports:
          - containerPort: 5000
{{- end }}
{{- end }}
