services:
  codegen:
    image: $CODEGEN 
    env_file: .env
    pull_policy: missing
    ports:
      - $PORT:5000
#    user: 1000:1000

  science:
    image: $SCIENCE 
    pull_policy: missing
    env_file: .env
    volumes:
      - sidecar-volume:/servicex/output
      #- /tmp/:/tmp/grid-security/:ro
      - /tmp/x509up_u1005/:/tmp/grid-security/x509up #:ro
      - $LOCAL_FOLDER:/generated
    tty: true
    depends_on:
      - codegen
#   user: 1000:1000

volumes:
  sidecar-volume:
