[tool.poetry]
name = "did-finder-cernopendata"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "did_finder_cernopendata", from = "src"}]

[tool.poetry.dependencies]
python = "~3.10"
<<<<<<< HEAD
servicex-did-finder-lib = "^2.0.3"
=======
servicex-did-finder-lib = "^3.0.0-alpha.1"
>>>>>>> 9ab73753 (Migrated CERN Opendata DID finder to Celery)

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.4"
pytest-asyncio = "^0.19.0"
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
