dependencies:
  - name: rabbitmq
    version: 7.6.*
    repository: https://charts.bitnami.com/bitnami/
  - name: minio
    version: ">=9.0.0"
    repository: https://charts.bitnami.com/bitnami/
    condition: objectStore.enabled
  - name: postgresql
    version: 8.3.*
    repository: https://charts.bitnami.com/bitnami/
    condition: postgres.enabled
