dependencies:
  - name: rabbitmq
    version: 7.6.*
    repository: https://charts.bitnami.com/bitnami/
  - name: minio
    version: ">=5.0.32"
    repository: https://helm.min.io/
    condition: objectStore.internal, objectStore.enabled
  - name: postgresql
    version: 8.3.*
    repository: https://charts.bitnami.com/bitnami/
    condition: postgres.enabled
