# Default values for servicex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



# Enable deployment of Minio Object Store with this chart - use this if you
# want to have the option of delivering results as parquet files
objectStore:
    enabled: true
    publicURL:

# Enable deployment of a full postgres sql database. This is advisable for
# bigger clusters where there will be several workers hitting the database
# at the same time. If not, the service will use sqlite
postgres:
    enabled: false


# Settings for the Flask App
app:
  image: sslhep/servicex_app
  tag: v1.0-rc.1
  pullPolicy: IfNotPresent
  replicas: 1
  auth: false
  validateTransformerImage: true

  # Create an initial admin user to manage new user workflow
  adminEmail: admin@example.com
  adminPassword: changeme

  # JWT remains valid for 6 hours
  authTimeout: 21600

  ingress:
    enabled: false
    host: uc.ssl-hep.org
    defaultBackend: default-http-backend

  # RabbitMQ can take up to one minute to start up. Simplify app startup by waiting for it
  rabbitmq:
    retries: 12
    retry_interval: 10 # seconds

# Settings for the DID Finder
didFinder:
  image: sslhep/servicex-did-finder
  tag: v1.0-rc.1
  pullPolicy: IfNotPresent
  rucio_host: https://voatlasrucio-server-prod.cern.ch:443
  auth_host: https://voatlasrucio-auth-prod.cern.ch:443
  threads: 5

  site:

# Settings for the preflight checker - this usually uses the same image as
# the transformer
preflight:
  image: sslhep/servicex_func_adl_xaod_transformer
  # For uproot deployment
  # image: sslhep/servicex_func_adl_uproot_transformer
  tag: v1.0-rc.1
  pullPolicy: IfNotPresent

#
# Code Generator service
codeGen:
  enabled: true
  image: sslhep/servicex_code_gen_func_adl_xaod
  # For uproot deployment
  # image: sslhep/servicex_code_gen_func_adl_uproot
  tag: v1.0-rc.1
  pullPolicy: IfNotPresent


# Pull policy for the worker pods - the image and version are specified as
# part of the transform request
transformer:
  pullPolicy: IfNotPresent
  autoscalerEnabled: false
  cpuLimit: 1


x509Secrets:
  image: sslhep/x509-secrets
  tag: v1.0-rc.1
  pullPolicy: IfNotPresent
  vomsOrg: atlas


# Settings for sending logging messages to an elasticsearch service
elasticsearchLogging:
  enabled: False
  host: 'host'
  port: 9200
  user: 'user account'
  password: 'password'

# Values for the RabbitMQ Chart
rabbitmq:
  # For easy testing we don't require PVs for rabbit
  persistence:
    enabled: false
  rabbitmq:
    password: leftfoot1
  # This is needed for Windows users
  volumePermissions:
      enabled: true


# Values for the Postgresql Chart
postgresql:
  postgresqlDatabase: servicex
  postgresqlPassword: leftfoot1
  persistence:
    enabled: false


# Values for Minio Chart
minio:
  # For easy testing we don't require PVs for minio
  persistence:
    enabled: false
  accessKey: miniouser
  secretKey: leftfoot1



###### Settings for Authenticating with the CERN Infrastructure #######

gridAccount: <your account>

rbacEnabled: True
