[tool.poetry]
name = "code-generator-python"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "code_generator_python"}]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.2"
Flask-RESTful = "^0.3.8"
Flask-WTF = "^1.0.1"
gunicorn = "^20.1.0"

[tool.poetry.extras]
pytest = ["pytest"]
coverage = ["coverage"]
codecov = ["codecov"]
flake8 = ["flake8"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
