"""V1.0-RC.2

Revision ID: 99e97a63d1bd
Revises: b389abb05262
Create Date: 2020-07-25 16:49:02.090979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e97a63d1bd'
down_revision = 'b389abb05262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('failure_description', sa.String(length=10485760), nullable=True))
    op.add_column('requests', sa.Column('status', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status')
    op.drop_column('requests', 'failure_description')
    # ### end Alembic commands ###
