"""rc4a2

Revision ID: a33a96f0f035
Revises: 04b9fb8ffee1
Create Date: 2021-06-10 13:43:28.447134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33a96f0f035'
down_revision = '04b9fb8ffee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('finish_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'finish_time')
    # ### end Alembic commands ###
