---
{{ if .Values.didFinder.atlasopenmagic.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-did-finder-atlasopenmagic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-did-finder-atlasopenmagic
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-did-finder-atlasopenmagic
      {{- with .Values.didFinder.atlasopenmagic.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.didFinder.atlasopenmagic.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.didFinder.atlasopenmagic.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.didFinder.atlasopenmagic.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: check-url
          image: {{ .Values.app.checksImage }}
          env:
          - name: URL
            value: "http://{{ .Release.Name }}-servicex-app:8000"
      containers:
      - name: {{ .Release.Name }}-did-finder-atlasopenmagic
        image: {{ .Values.didFinder.atlasopenmagic.image }}:{{ .Values.didFinder.atlasopenmagic.tag }}
        imagePullPolicy: {{ .Values.didFinder.atlasopenmagic.pullPolicy }}
        {{- if .Values.didFinder.atlasopenmagic.resources }}
        resources:
{{ toYaml .Values.didFinder.atlasopenmagic.resources | indent 10 }}
        {{- end }}

        env:
          - name: INSTANCE_NAME
            value: {{ .Release.Name }}
        {{- if .Values.secrets }}
          - name: RMQ_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets }}
                key: rabbitmq-password
          - name: BROKER_URL
            value: amqp://user:$(RMQ_PASS)@{{ .Release.Name }}-rabbitmq:5672/?heartbeat=9000
        {{- else }}
          - name: BROKER_URL
            value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:5672/%2F
        {{- end }}
        {{- if .Values.logging.logstash.enabled }}
          - name: LOGSTASH_HOST
            value: "{{ .Values.logging.logstash.host }}"
          - name: LOGSTASH_PORT
            value: "{{ .Values.logging.logstash.port }}"
        {{- end }}

{{ end }}
