language: python
services:
  - docker
python:
- '3.6'
install:
- pip install -e .
- pip install ".[test]"
- pip install pytest coverage codecov flake8
script:
- flake8
- coverage run -m pytest -s
- codecov
- docker build -t sslhep/servicex_app:pytest
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
env:
  global:
    docker_user:
      secure: FzhLTOeQcenqmX3DEARz5GeV0g2OvcQihYn2QPKKOP2aeRomCDB9n//VsJY9uwY29tugfpK5HRn49g4c9JQPBEHpNt9ZFmgMy2Rnm1WopEEZLoOl51yhb+NgTs23jix3OTQcvODnY+VpGbQO6RO6VrkaNZi7JN2zpCST9QpMLhqBLpeHsB6VBFN04NSZAkqPZ/1zwNApk0BaP8CTpr9K+SC/wnCdJToImCkoENcrDw6DKKnVuBhBKKwiiKUcSGqBga55LbR/fixY1Fe0+PT6RCwMhJk5HRRpvYisZhJBTHuIUezLp2cYeiOMfTlLmmRFQuh5kavrHrwXW3jwLNfy1ND1CWv1rdkBVoZ+vid59i8julKiXZttOBU+eNkSSVGPBXbdRlNeziEOfcsN5+3Xegnc9rHkWLxHqwN2F5C6n53JXjs6etxrMnjlvznbXH+JQFqX9y6O1H7jWbRPFZubM0AiiVB6/0MXEXWnO1rdiBsXsMa6Dl5awmyz6lHpWHup385GeFyE3TcLAWxYLxr1yjaYyOmvbqLy5gb+y2QcBK9QTtT3o5vh4haI//5FH4BU4YYmpEzGibwe78eymhmGNKlQDZero3pqMH/qvsePOp74yeNKs2lAhVhWY6jvolRiGdh/U3/rRNMXjC+Ww51u0U/R+D2TUEbf+pIvMHZ9Cx0=
    docker_password:
      secure: "M1KZcYSfLFjeFbYbG5P4EtUVLJvDoNPf40X3eKW/5LHSwWgPEz7lPBo0QrojoaVnrRS3BTc5BjSBkwHy3skZmb1GOKBluc4V+eANm7KBpkRIJFQUF7FdV4yQ8P5d9h9DKBgFlxZ6c1vUAYtP6fBM7rqwhlCxVAZkhWUWp1jMmNDjWQdQ7RqIthjFWhPkHSKHA/VPL9Qu+I4rfexstn1x+HJwqpE/1GinP0gQEG4i7Sez+jpK2vDSa3N6We7dR3EXXqOqLVoB/EetjCt7XhWqyfoSKpg/l3jzhkxYcLM5v+2+grW94qTpMqR2UfRaBzdzLlct+DX90/r3Pa9HSie86X7psItsZKNBDY9H5x+7wrRZLH7b/ZWMVZ2zDgM8HamrGgv71a87DF/qb3/epEfgXPZ49/DZJwn3nOSarWJI2qPmAMDr6pPwJk2T31/b/zT/VvqNKIoSm/DgBnuhkiM4UOGi8sKK7VjomtV0F5OKbypIyMJtlrrWNriOwsvpVy3FTV18bve8rrvUUn+iDdSuoJU/5abDcTztTCkFOj0yfBgsQzdwvkFp/iLsc07mVzzAPBFsfg7Y1jsXRvmZn2Q0tRGfDNTSxGPHH2TV7VSif3B3/g/vcoWbsNeivdO8Hv9FbL+BzWhNvZsEbRY38bKuMUsmYX3+QY8MLd0zTZFeOUI="


