language: python
python:
  - "3.6"

install:
  - pip install -e .
  - pip install ".[test]"
  - pip install pytest coverage codecov flake8

script:
  - flake8
  - coverage run -m pytest -s
  - codecov