language: python
services:
  - docker
python:
- '3.6'
install:
- pip install -e .
- pip install ".[test]"
- pip install pytest coverage codecov flake8
script:
- flake8
- coverage run -m pytest -s
- codecov
- docker build -t sslhep/servicex_app:pytest
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

