noCerts: false
didFinder:
  rucio:
    enabled: true
    tag: root_to_parquet
    pullPolicy: Always

  CERNOpenData:
    enabled: false

  YT:
    enabled: false
app:
  tag: root_to_parquet
  pullPolicy: Always
  validateTransformerImage: false
  checksImage: shriram192/checks:latest

transformer:
  pullPolicy: Always
  cachePrefix: ""
  autoscalerEnabled: false
  sidecarTag: root_to_parquet
  sidecarPullPolicy: IfNotPresent

#  language: python
#  exec: /generated/transform_single_file.py
#  defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer

  language: bash
  exec: /generated/transform_single_file.sh
  scienceContainerPullPolicy: Always

codeGen:
  #image: sslhep/servicex_code_gen_func_adl_uproot
  image: sslhep/servicex_code_gen_atlas_xaod
  tag: root_to_parquet
  pullPolicy: Always
  defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
  defaultScienceContainerTag: sidecar-monorepo

objectStore:
  enabled: true
  publicURL: localhost:9000
  publicClientUseTLS: false


rabbitmq:
  auth:
    erlangCookie: mmmmmmmcoookie
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30672

postgres:
    enabled: true

gridAccount: bgalewsk