noCerts: false
didFinder:
  unzip:
    enabled: true
    tag: pandas-tf
    pullPolicy: Always
    image: sslhep/servicex-did-finder-unzip
  rucio:
    enabled: true
    tag: pandas-tf
    pullPolicy: Always
    image: sslhep/servicex-did-finder
  CERNOpenData:
    enabled: false

  YT:
    enabled: false
app:
  tag: pandas-tf
  pullPolicy: IfNotPresent
  validateTransformerImage: false
  checksImage: shriram192/checks

transformer:
  autoscalerEnabled: false
  sidecarTag: pandas-tf
  sidecarPullPolicy: IfNotPresent

#  language: python
#  exec: /generated/transform_single_file.py
#  defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer

  language: bash
  exec: /generated/transform_single_file.sh
  scienceContainerPullPolicy: IfNotPresent

codeGen:
  python:
    enabled: true
    image: sslhep/servicex_code_gen_python
    pullPolicy: Always
    tag: pandas-tf
    defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer
    defaultScienceContainerTag: pandas-tf
    type: unzip
  uproot:
    enabled: false
  cms:
    enabled: false

objectStore:
  enabled: true
  publicURL: localhost:9000
  publicClientUseTLS: false


rabbitmq:
  auth:
    erlangCookie: mmmmmmmcoookie
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30672


postgres:
    enabled: true

gridAccount: bgalewsk