noCerts: false
didFinder:
  rucio:
    enabled: true

  CERNOpenData:
    enabled: false

  YT:
    enabled: false

transformer:
  pullPolicy: Always
  autoscalerEnabled: false


objectStore:
  enabled: true
  publicURL: localhost:9000
  publicClientUseTLS: false

codeGen:
  image: sslhep/servicex_code_gen_func_adl_xaod
  tag: develop
  defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
  defaultScienceContainerTag: develop

rabbitmq:
  auth:
    erlangCookie: mmmmmmmcoookie
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30672


postgres:
    enabled: true

gridAccount: bgalewsk