dependencies:
  - name: rabbitmq
    version: 11.16.2
    repository: https://charts.bitnami.com/bitnami/
  - name: minio
    version: 11.10.26
    repository: https://charts.bitnami.com/bitnami/
    condition: objectStore.internal, objectStore.enabled
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami/
    condition: postgres.enabled
  - name: prometheus
    version: 29.35.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
  - name: grafana
    version: 10.5.15
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.enabled
  - name: tempo
    version: 1.24.4
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.tracing.enabled
