dependencies:
  - name: rabbitmq
    version: 16.0.*
    repository: https://charts.bitnami.com/bitnami/
  - name: minio
    version: 17.0.*
    repository: https://charts.bitnami.com/bitnami/
    condition: objectStore.internal, objectStore.enabled
  - name: postgresql
    version: 16.7.*
    repository: https://charts.bitnami.com/bitnami/
    condition: postgres.enabled
