app:
  adminEmail: admin@example.com
  auth: false
  auth_type: globus
  authExpires: 21600
  checksImage: ncsa/checks:latest
  defaultDIDFinderScheme: null
  globusClientID: null
  globusClientSecret: null
  defaultUsers:
  image: sslhep/servicex_app
  ingress:
    class: nginx
    defaultBackend: default-http-backend
    enabled: false
    host: servicex.ssl-hep.org
    tls:
      clusterIssuer: null
      enabled: false
      secretName: "{{.Release.Name}}-app-tls"
  logLevel: INFO
  mailgunApiKey: null
  mailgunDomain: null
  pullPolicy: Always
  rabbitmq:
    retries: 12
    retry_interval: 10
  replicas: 1
  tag: develop
  tokenExpires: false
  validateTransformerImage: true
codeGen:
  enabled: true
  image: sslhep/servicex_code_gen_atlas_xaod
  pullPolicy: Always
  tag: develop
  defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
  defaultScienceContainerTag: develop
didFinder:
  CERNOpenData:
    cachePrefix: null
    enabled: true
    image: sslhep/servicex-did-finder-cernopendata
    pullPolicy: Always
    tag: develop
  rucio:
    auth_host: https://voatlasrucio-auth-prod.cern.ch:443
    cachePrefix: null
    enabled: true
    image: sslhep/servicex-did-finder
    memcache:
      enabled: true
      image: memcached
      tag: alpine
      ttl: 86400
    pullPolicy: Always
    reportLogicalFiles: false
    rucio_host: https://voatlasrucio-server-prod.cern.ch:443
    servicex_latitude: 41.78
    servicex_longitude: -87.7
    tag: develop
gridAccount: <your account>
logging:
  logstash:
    enabled: true
    host: servicex.atlas-ml.org
    port: 5959
    protocol: TCP
    monitor: "https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/c2cc1f30-4a5b-11ed-afcf-d91dad577662?embed=true&_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-24h%2Fh%2Cto%3Anow))&show-time-filter=true"
    logs: "https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/bb682100-5558-11ed-afcf-d91dad577662?embed=true&_g=(filters%3A!(('%24state'%3A(store%3AglobalState)%2Cmeta%3A(alias%3A!n%2Cdisabled%3A!f%2Cindex%3A'923eaa00-45b9-11ed-afcf-d91dad577662'%2Ckey%3Ainstance%2Cnegate%3A!f%2Cparams%3A(query%3Aservicex)%2Ctype%3Aphrase)%2Cquery%3A(match_phrase%3A(instance%3A{{ .Release.Name }}))))%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-24h%2Fh%2Cto%3Anow))&show-query-input=true&show-time-filter=true&hide-filter-bar=true"
minio:
  auth:
    rootPassword: leftfoot1
    rootUser: miniouser
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 60
  persistence:
    enabled: false
noCerts: false
objectStore:
  enabled: true
  internal: true
  publicClientUseTLS: true
  publicURL: null
  useTLS: false
postgres:
  enabled: false
postgresql:
  global:
    postgresql:
      auth:
        database: servicex
        postgresPassword: leftfoot1
  primary:
    resources:
      requests:
        # for production instances this should be set to 2 CPUs.
        cpu: 250m
    persistence:
      enabled: false
rabbitmq:
  auth:
    password: leftfoot1
  persistence:
    enabled: false
  volumePermissions:
    enabled: true
rbacEnabled: true
secrets: null
transformer:
  autoscaler:
    cpuScaleThreshold: 30
    enabled: true
    maxReplicas: 20
    minReplicas: 1
  cpuLimit: 1

  sidecarImage: sslhep/servicex_sidecar_transformer
  sidecarTag: develop
  sidecarPullPolicy: Always
  scienceContainerPullPolicy: Always

  language: python
  exec:  # replace me
  outputDir: /servicex/output

  persistence:
    existingClaim: null
    subdir: null
  priorityClassName: null
x509Secrets:
  image: sslhep/x509-secrets
  initImage: alpine:3.6
  pullPolicy: Always
  tag: develop
  vomsOrg: atlas
minioCleanup:
  enabled: false
  image: sslhep/servicex_minio_cleanup
  threads: "6"
  logLevel: "INFO"
  pullPolicy: Always
  tag: develop
  schedule: "* */8 * * *"
  maxAge: 30
  maxSize: "1G"
  normSize: "700M"
