app:
  environment: production
  mountLocal: false
  adminEmail: admin@example.com
  auth: false
  authExpires: 21600
  checksImage: ncsa/checks:main
  defaultDIDFinderScheme: null
  oauthMetadataURL: null
  oauthClientID: null
  oauthClientSecret: null
  allowAllAfterAuth: false
  defaultUsers:
  image: sslhep/servicex_app
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2.5Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  ingress:
    class: nginx
    defaultBackend: default-http-backend
    enabled: false
    host: servicex.ssl-hep.org
    tls:
      clusterIssuer: null
      enabled: false
      secretName: "{{.Release.Name}}-app-tls"
  logLevel: INFO
  mailgunApiKey: null
  mailgunDomain: null
  pullPolicy: Always
  rabbitmq:
    retries: 12
    retry_interval: 10
  replicas: 1
  tag: develop
  tokenExpires: false
  validateTransformerImage: true
  sqlalchemyEngineOptions: null
  allowedImagePrefixes:
    - "docker.io/sslhep"
    - "sslhep/"
    - "gitlab-registry.cern.ch/"

codeGen:
  uproot-raw:
    enabled: true
    image: sslhep/servicex_code_gen_raw_uproot
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_science_image_combined_root
    defaultScienceContainerTag: 5.7.4-6.38.04
    compressionAlgorithm: ZSTD
    compressionLevel: 5
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  uproot:
    enabled: true
    image: sslhep/servicex_code_gen_func_adl_uproot
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_science_image_combined_root
    defaultScienceContainerTag: 5.7.4-6.38.04
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  python:
    enabled: true
    image: sslhep/servicex_code_gen_python
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_science_image_combined_root
    defaultScienceContainerTag: 5.7.4-6.38.04
    compressionAlgorithm: ZSTD
    compressionLevel: 5
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  rdataframe:
    enabled: true
    image: sslhep/servicex_code_gen_python
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_science_image_combined_root
    defaultScienceContainerTag: 5.7.4-6.38.04
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  atlasr21:
    enabled: true
    image: sslhep/servicex_code_gen_atlas_xaod
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
    defaultScienceContainerTag: 21.2.231
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  atlasr22:
    enabled: true
    image: sslhep/servicex_code_gen_atlas_xaod
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
    defaultScienceContainerTag: 22.2.107
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  atlasr25:
    enabled: true
    image: sslhep/servicex_code_gen_atlas_xaod
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
    defaultScienceContainerTag: 25.2.41
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  cmssw-5-3-32:
    enabled: false
    image: sslhep/servicex_code_gen_cms_aod
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_func_adl_cms_aod_transformer
    defaultScienceContainerTag: cmssw-5-3-32
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

  topcp:
    enabled: true
    image: sslhep/servicex_code_gen_topcp
    pullPolicy: Always
    tag: develop
    defaultScienceContainerImage: sslhep/servicex_science_image_topcp
    defaultScienceContainerTag: 25.2.74-v2.23.0
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

didFinder:
  CERNOpenData:
    enabled: true
    image: sslhep/servicex-did-finder-cernopendata
    pullPolicy: Always
    tag: develop
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}
  atlasopenmagic:
    enabled: true
    image: sslhep/servicex-did-finder-atlasopenmagic
    pullPolicy: Always
    tag: develop
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}
  xrootd:
    enabled: true
    image: sslhep/servicex-did-finder-xrootd
    pullPolicy: Always
    tag: develop
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}
  rucio:
    auth_host: https://atlas-rucio-auth.cern.ch:443
    enabled: true
    image: sslhep/servicex-did-finder
    pullPolicy: Always
    reportLogicalFiles: false
    rucio_host: https://voatlasrucio-server-prod.cern.ch:443
    servicex_latitude: 41.78
    servicex_longitude: -87.7
    tag: develop
    replicaSorterEnabled: false
    geoIPURL: null
    geoIPEdition: null
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}

gridAccount: <your account>
logging:
  logstash:
    enabled: true
    host: servicex.atlas-ml.org
    port: 5959
    protocol: TCP
    monitor: "https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/c2cc1f30-4a5b-11ed-afcf-d91dad577662?embed=true&_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-24h%2Fh%2Cto%3Anow))&show-time-filter=true"
    # This URL format is tied to a parser in servicex_app/servicex_app/web/kibana_url_filter.py
    logs: "https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/bb682100-5558-11ed-afcf-d91dad577662?embed=true&_g=(filters:!(),refreshInterval:(pause:!t,value:1000),time:(from:now-24h%2Fh,to:now))&_a=(filters:!((query:(match_phrase:(instance:{{.Release.Name}})))),index:'923eaa00-45b9-11ed-afcf-d91dad577662')"
minio:
  image:
    repository: bitnamilegacy/minio
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r51
  auth:
    rootPassword: leftfoot1
    rootUser: miniouser
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 60
  persistence:
    enabled: false
noCerts: false
objectStore:
  enabled: true
  internal: true
  publicClientUseTLS: true
  publicURL: null
  useTLS: false
postgres:
  enabled: false
postgresql:
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r51
  global:
    postgresql:
      auth:
        database: servicex
        postgresPassword: leftfoot1
  primary:
    resources:
      requests:
        # for production instances this should be set to 2 CPUs.
        cpu: 250m
    persistence:
      enabled: false
rabbitmq:
  image:
    repository: bitnamilegacy/rabbitmq
  auth:
    password: leftfoot1
  persistence:
    enabled: false
  volumePermissions:
    enabled: true
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r51
  extraConfiguration: |-
    consumer_timeout = 3600000

rbacEnabled: true
secrets: null
transformer:
  # The transformers will prepend an xCache URL with this prefix to each of
  # the files that are being accessed. This can be a single value or a
  # comma-separated list of values.
  # Do not put root:// in these values.
  cachePrefix: null
  # Alternatively, provide the virtual placement service site name to look up
  # xCache servers from
  cacheVPSSite: null
  cacheVPSCheckInterval: 1800
  cacheVPSLivenessURL: https://vps.cern.ch/liveness


  autoscaler:
    cpuScaleThreshold: 30
    enabled: true
    maxReplicas: 20
    minReplicas: 1
  cpuLimit: 1
  memoryLimit: 2Gi
  cpuRequest: 500m
  memoryRequest: 512Mi

  sidecarImage: sslhep/servicex_sidecar_transformer
  sidecarTag: develop
  sidecarPullPolicy: IfNotPresent
  scienceContainerPullPolicy: IfNotPresent

  language: python
  exec:           # replace me
  outputDir: /servicex/output

  persistence:
    existingClaim: null
    subdir: null
  priorityClassName: null
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
x509Secrets:
  image: sslhep/x509-secrets
  initImage: alpine:3.6
  pullPolicy: Always
  tag: develop
  vomsOrg: atlas
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

scheduledTasks:
  # image should support curl, gnu date
  image: python
  tag: "3.10"
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

  # This cleans up the output object store caches and archives associated transforms.
  dataLifecycle:
    enabled: false
    schedule: "0 */8 * * *"

    # We will archive any transforms older than this. Use the gnu date command
    # --date argument.
    # See https://www.geeksforgeeks.org/date-command-linux-examples/#4-how-to-display-past-dates
    # for examples
    retention: "7 days ago"

    # The cleanup service will go beyond the retention date to keep the server side cache size below
    # this threshold. Specify this as a string with Mb, Gb, Tb or Pb units in the string
    maxDesiredCacheSize: "1Tb"

  # This obsoletes the dataset cache for datasets older than "cacheLifetime" hours.
  # Does not touch transforms or output files.
  datasetLifecycle:
    schedule: "0 * * * *"

    # How long to keep datasets in the cache, in hours
    cacheLifetime: 24

  # This cleans up lingering Kubernetes resources from unclean shutdowns of transformers.
  kubernetesCleanup:
    enabled: true
    schedule: "0 0 * * *"

    # Delete transforms older than this value, in hours
    maxAge: 168
