---
{{ if .Values.didFinder.girder.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-did-finder-girder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-did-finder-girder
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-did-finder-girder
    spec:
      containers:
      - name: {{ .Release.Name }}-did-finder-girder
        image: {{ .Values.didFinder.girder.image }}:{{ .Values.didFinder.girder.tag }}
        imagePullPolicy: {{ .Values.didFinder.girder.pullPolicy }}
        env:
          - name: INSTANCE_NAME
            value: {{ .Release.Name }}
        {{- if .Values.secrets }}
          - name: RMQ_PASS 
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets }}
                key: rabbitmq-password
        {{- end }}
        args:
          - --rabbit-uri
    {{- if .Values.secrets }}
          - amqp://user:$(RMQ_PASS)@{{ .Release.Name }}-rabbitmq:5672
    {{- else }}
          - amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:5672
    {{- end }}
{{ end }}
