apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: servicex
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: servicex
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:5.0.5
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        # args: ["--save","\"\""]
        resources:
          requests:
            cpu: 900m
            memory: 200Gi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-conf-volume
          mountPath: "/etc/redis/"
      volumes:
      - name: redis-conf-volume
        secret:
          secretName: redis-master-conf
          items:
          - key: conf
            path: redis.conf   