apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer
  namespace: redis
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master
  type: LoadBalancer