[tool.poetry]
name = "transformer-sidecar"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "transformer_sidecar"}]

[tool.poetry.dependencies]
python = "~3.7"
servicex-transformer = "^1.0.3"
pika = "1.1.0"
rabbitmq = "^0.2.0"
pyarrow = "0.16.0"
psutil = "^5.9.2"
watchdog = "^2.1.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
