{{- if .Values.logging.vector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicex.vector.aggregatorHost" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ include "servicex.vector.aggregatorHost" . }}
spec:
  ports:
   # The app's logger writes newline-delimited JSON here.
   - port: {{ .Values.logging.vector.port }}
     targetPort: socket
     name: "socket"
     protocol: TCP
   # Transformer pods' vector containers forward here over the native protocol.
   - port: {{ .Values.logging.vector.aggregator.port }}
     targetPort: vector
     name: "vector"
     protocol: TCP
  selector:
    app: {{ include "servicex.vector.aggregatorHost" . }}
  type: ClusterIP
{{- end }}
