{{- if .Values.codeGen.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-code-gen
spec:
  ports:
   - port: 8000
     targetPort: 5000
     name: "tcp"
     protocol: TCP
  selector:
    app: {{ .Release.Name }}-code-gen
  type: ClusterIP
{{- end }}
