---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-did-finder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-did-finder
    spec:
      containers:
      - name: {{ .Release.Name }}-did-finder
        image: {{ .Values.didFinder.image }}:{{ .Values.didFinder.tag }}
        command: ["bash","-c"]
        args: ["/usr/src/app/proxy-exporter.sh & sleep 5 && env PYTHONPATH=./did_finder python scripts/did_finder.py --rabbit-uri amqp://user:leftfoot1@{{ .Release.Name }}-rabbitmq:5672/%2F {{ if .Values.didFinder.staticFile }} --staticfile {{ .Values.didFinder.staticFile }} {{ end }}"]
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.didFinder.pullPolicy }}
        volumeMounts:
          - name: rucio-cfg
            mountPath: /opt/rucio/etc/
          - name: did-finder-cfg
            mountPath: /usr/src/app/config/
          - name: x509-secret
            mountPath: /etc/grid-security-ro
            readOnly: true

      volumes:
        - name: rucio-cfg
          configMap:
            name: {{ .Release.Name }}-rucio-config
        - name: did-finder-cfg
          configMap:
            name: {{ .Release.Name }}-did-finder-config
        - name: x509-secret
          secret:
            defaultMode: 292
            secretName: {{ .Release.Name }}-x509-proxy
