apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-did-finder-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  config.json: |
    {
        "TESTING": false,
        "SITENAME": "servicex.slateci.net",
        "ES_HOST": "atlas-kibana.mwt2.org:9200",
        "SITE": "MWT2"
    }