apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grid-secrets
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
type: Opaque
data:
  secrets.txt: "{{ .Values.gridPassword | b64enc }}"
