apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grid-certs-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  userkey.pem.b64: "{{ .Values.userkey  | b64enc | indent 2 }}"
  usercert.pem.b64: "{{ .Values.usercert | b64enc | indent 2 }}"
