{{- if .Values.app.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: {{ .Release.Name }}-servicex
  name: {{ .Release.Name }}-servicex-ingress
spec:
  rules:
  - host: {{ .Release.Name }}-servicex.{{ .Values.app.ingress.host }}
    http:
      paths:
      {{- if .Values.objectStore.enabled }}
      - path: /minio
        backend:
          serviceName: {{ .Release.Name }}-minio
          servicePort: 9000
      {{- end }}
      - path: /servicex/internal
        backend:
          serviceName: {{ .Values.app.ingress.defaultBackend }}
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-servicex-app
          servicePort: 8000
{{- end }}
