---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-preflight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-preflight
    spec:
      containers:
      - name: {{ .Release.Name }}-preflight
        image: {{ .Values.preflight.image }}:{{ .Values.preflight.tag }}
        command: ["bash","-c"]
        env:
          - name: "BASH_ENV"
            value: "/home/atlas/.bashrc"
        args: ["/home/atlas/proxy-exporter.sh & sleep 5 && python validate_requests.py --rabbit-uri amqp://user:leftfoot1@{{ .Release.Name }}-rabbitmq:5672/%2F"]
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.preflight.pullPolicy }}
        volumeMounts:
          - name: x509-secret
            mountPath: /etc/grid-security-ro
            readOnly: true

          {{ if .Values.hostMount }}
          - name: rootfiles
            mountPath: /data
          {{ end }}
      volumes:
        - name: x509-secret
          secret:
            defaultMode: 292
            secretName: {{ .Release.Name }}-x509-proxy
        {{ if .Values.hostMount }}
        - name: rootfiles
          hostPath:
            path: {{ .Values.hostMount }}
        {{ end }}

