---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-x509-secrets
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-x509-secrets
    spec:
      serviceAccountName: {{ template "servicex.fullname" . }}
      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3.6
          command: ["/bin/sh","-c"]
          args: ["base64 -d /etc/grid-certs-ro/usercert.pem.b64 > /etc/grid-certs/usercert.pem; chmod 600 /etc/grid-certs/usercert.pem; base64 -d /etc/grid-certs-ro/userkey.pem.b64 > /etc/grid-certs/userkey.pem; chmod 400 /etc/grid-certs/userkey.pem"]
          volumeMounts:
          - name: grid-certs-rw-copy
            mountPath: /etc/grid-certs/
          - name: grid-certs-cfg
            mountPath: /etc/grid-certs-ro/
      containers:
      - name: {{ .Release.Name }}-x509-secrets
        image: {{ .Values.x509Secrets.image }}:{{ .Values.x509Secrets.tag }}
        command: ["bash","-c"]
        args: ["python x509_updater.py --secret {{ .Release.Name }}-x509-proxy --voms {{ .Values.x509Secrets.vomsOrg }}"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.x509Secrets.pullPolicy }}
        volumeMounts:
          - name: grid-certs-rw-copy
            mountPath: /etc/grid-certs/
          - name: grid-secret
            mountPath: /servicex/
          - name: grid-certs-cfg
            mountPath: /etc/grid-certs-ro/

      volumes:
        - name: grid-certs-cfg
          configMap:
            name: {{ .Release.Name }}-grid-certs-config
            defaultMode: 400
        - name: grid-certs-rw-copy
          emptyDir: {}
        - name: grid-secret
          secret:
            secretName: {{ .Release.Name }}-grid-secrets
