{{- if .Values.rbacEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "servicex.fullname" . }}-job-manager
  labels:
    app: {{ template "servicex.name" . }}
    chart: {{ template "servicex.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "servicex.fullname" . }}-x509-secret-manager
  labels:
    app: {{ template "servicex.name" . }}
    chart: {{ template "servicex.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "servicex.fullname" . }}-configmap-manager
  labels:
    app: {{ template "servicex.name" . }}
    chart: {{ template "servicex.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

{{- end }}