apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-dataset-lifecycle-job
spec:
  schedule: {{ .Values.scheduledTasks.datasetLifecycle.schedule | default  "0 * * * *" | quote  }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-dataset-lifecycle-job
        spec:
          containers:
          - name: {{ .Release.Name }}-dataset-lifecycle-job
            image: {{ .Values.scheduledTasks.image }}:{{ .Values.scheduledTasks.tag }}
            imagePullPolicy: {{ .Values.scheduledTasks.pullPolicy }}
            env:
              - name: LIFETIME
                value: "{{ .Values.scheduledTasks.datasetLifecycle.cacheLifetime }}"
            command:
            - /usr/bin/curl
            - --request POST "http://{{ .Release.Name }}-servicex-app:8000/servicex/internal/dataset-lifecycle?age=$(LIFETIME)"
          restartPolicy: OnFailure
