apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-dataset-lifecycle-job
spec:
  schedule: {{ .Values.scheduledTasks.datasetLifecycle.schedule | default  "0 * * * *" | quote  }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-dataset-lifecycle-job
          {{- with .Values.scheduledTasks.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.scheduledTasks.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduledTasks.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduledTasks.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ .Release.Name }}-dataset-lifecycle-job
            image: {{ .Values.scheduledTasks.image }}:{{ .Values.scheduledTasks.tag }}
            imagePullPolicy: {{ .Values.scheduledTasks.pullPolicy }}
            {{- if .Values.scheduledTasks.resources }}
            resources:
{{ toYaml .Values.scheduledTasks.resources | indent 14 }}
            {{- end }}
            env:
              - name: LIFETIME
                value: {{ .Values.scheduledTasks.datasetLifecycle.cacheLifetime | quote }}
            command:
            - /usr/bin/curl
            - --json
            - '{"age": $(LIFETIME)}'
            - "http://{{ .Release.Name }}-servicex-app:8000/servicex/internal/dataset-lifecycle"
          restartPolicy: OnFailure
