/**
 * ServiceX API
 * An API for client submitting requests for the data delivery, requesting event batches, returning processing status.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: ilijav@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DataSpec (
  /* Rucio did */
  did: String,
  /* List of tags. Not implemented now. */
  tags: Option[Seq[String]] = None,
  /* Number of events to deliver */
  eventsToDeliver: Option[Int] = None,
  /* MB to deliver */
  mbToDeliver: Option[Int] = None,
  format: Option[DataSpecEnums.Format] = None,
  /* columns (branches) to deliver */
  columns: Seq[String]
) extends ApiModel

object DataSpecEnums {

  type Format = Format.Value
  object Format extends Enumeration {
    val PandasDataframe = Value("pandas dataframe")
    val SparkDataframe = Value("spark dataframe")
    val Ntup = Value("ntup")
  }

}

