/**
 * ServiceX API
 * An API for client submitting requests for the data delivery, requesting event batches, returning processing status.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: ilijav@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RequestStatus (
  /* unique token that identifies this data request */
  token: String,
  status: RequestStatusEnums.Status,
  stats: Option[RequestStatusStats] = None
) extends ApiModel

object RequestStatusEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Initializing = Value("initializing")
    val Prefetching = Value("prefetching")
    val Serving = Value("serving")
    val Finished = Value("finished")
    val Terminated = Value("terminated")
  }

}

