#%RAML 1.0
---
title: ServiceX API
baseUri: https://servicex.slateci.net
version: v1

/healthz:
  get
    description: | liveness probe to be used by k8s deployment
    headers: 
    body: 
    responses: 
/user:
  /login:
  /logout:
  /

/users:
  /authors:
    /{authorname}:
        get:
            
  /books:
    get
        description: |
        headers: 
        body: 
        responses: 
