apiVersion: v1
kind: PersistentVolume
metadata:
  name: transformer-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "<<< Path to your local directory >>>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transformer-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi