"""v1.0-rc4-a1

Revision ID: a6cbb6201d3d
Revises: dd1f9a8a2aee
Create Date: 2021-05-01 15:19:59.936722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cbb6201d3d'
down_revision = 'dd1f9a8a2aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'title')
    # ### end Alembic commands ###
