"""V1.0-RC.3

Revision ID: dd1f9a8a2aee
Revises: 99e97a63d1bd
Create Date: 2020-08-11 16:59:41.311733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1f9a8a2aee'
down_revision = '99e97a63d1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # Drop and recreate user table
    op.drop_table('users')
    op.create_table('users',
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('experiment', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('sub', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('refresh_token')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('key', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_column('users', 'sub')
    op.drop_column('users', 'refresh_token')
    op.alter_column('users', 'name', new_column_name='full_name')
    # ### end Alembic commands ###
